# Generated by Django 2.1.1 on 2020-06-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chartdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_quarter_risk', models.FloatField()),
                ('second_quarter_risk', models.FloatField()),
                ('third_quarter_risk', models.FloatField()),
                ('quarter_risk', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rankingdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank_risk', models.IntegerField()),
                ('Cor_name', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=15)),
                ('Cor_Risk', models.FloatField()),
            ],
        ),
    ]
