# Generated by Django 2.1.1 on 2020-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20200610_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='GJ_risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Risk', models.FloatField()),
                ('Cor_code', models.IntegerField()),
                ('ODD', models.IntegerField()),
                ('PFS', models.IntegerField()),
                ('DMR', models.IntegerField()),
                ('ETC', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JN_risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Risk', models.FloatField()),
                ('Cor_code', models.IntegerField()),
                ('ODD', models.IntegerField()),
                ('PFS', models.IntegerField()),
                ('DMR', models.IntegerField()),
                ('ETC', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='GJrisk',
        ),
        migrations.DeleteModel(
            name='JNrisk',
        ),
    ]
